### ISSUE TITLE
Shorthand hex codes

### ISSUE THREAD

**Issue by stephenway** [scottcorgan/hex-to-rgb#1]
Looks like testing
`t.deepEqual(hexToRgb('#fff'), [255,255,255], 'white converted with hash');`
does not pass, it is a common use case, how would this get fixed?

Thanks

**Comment by scottcorgan** [comment]
Can you open a PR with a failing test?

**Comment by scottcorgan** [comment]
Good find. Published as `1.0.1`

**Comment by stephenway** [comment]
Thanks for the quick turn around @scottcorgan
